[package]
name = "c-string-escape"
version = "0.1.0"
authors = ["JP3BGY <6635381+JP3BGY@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
